package modle;
// Generated 2016/1/18 �U�� 06:26:11 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "Member", catalog = "bakeryDB", uniqueConstraints = @UniqueConstraint(columnNames = "Account") )
public class Member implements java.io.Serializable {

	private int memberId;
	private String account;
	private byte[] password;
	private String username;
	private String sex;
	private Date birth;
	private String email;
	private String phone;
	private String address;
	private Date logindate;
	private Date lastDate;
	private String fromfb;
	private byte[] picture;
	private int statu;
	private Integer point;
	private Integer orderMath;
	private String nickname;
	private String kanban;
	private Set<VotePerson> votePersons = new HashSet<VotePerson>(0);

	public Member() {
	}

	public Member(int memberId, String account, byte[] password, String username, int statu) {
		this.memberId = memberId;
		this.account = account;
		this.password = password;
		this.username = username;
		this.statu = statu;
	}

	public Member(int memberId, String account, byte[] password, String username, String sex, Date birth, String email,
			String phone, String address, Date logindate, Date lastDate, String fromfb, byte[] picture, int statu,
			Integer point, Integer orderMath, String nickname, String kanban, Set<VotePerson> votePersons) {
		this.memberId = memberId;
		this.account = account;
		this.password = password;
		this.username = username;
		this.sex = sex;
		this.birth = birth;
		this.email = email;
		this.phone = phone;
		this.address = address;
		this.logindate = logindate;
		this.lastDate = lastDate;
		this.fromfb = fromfb;
		this.picture = picture;
		this.statu = statu;
		this.point = point;
		this.orderMath = orderMath;
		this.nickname = nickname;
		this.kanban = kanban;
		this.votePersons = votePersons;
	}

	@Id

	@Column(name = "Member_id", unique = true, nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "Account", unique = true, nullable = false, length = 30)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "Password", nullable = false)
	public byte[] getPassword() {
		return this.password;
	}

	public void setPassword(byte[] password) {
		this.password = password;
	}

	@Column(name = "Username", nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Sex", length = 5)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Birth", length = 23)
	public Date getBirth() {
		return this.birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Logindate", length = 23)
	public Date getLogindate() {
		return this.logindate;
	}

	public void setLogindate(Date logindate) {
		this.logindate = logindate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_date", length = 23)
	public Date getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(Date lastDate) {
		this.lastDate = lastDate;
	}

	@Column(name = "Fromfb", length = 5)
	public String getFromfb() {
		return this.fromfb;
	}

	public void setFromfb(String fromfb) {
		this.fromfb = fromfb;
	}

	@Column(name = "Picture")
	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	@Column(name = "Statu", nullable = false)
	public int getStatu() {
		return this.statu;
	}

	public void setStatu(int statu) {
		this.statu = statu;
	}

	@Column(name = "Point")
	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

	@Column(name = "Order_math")
	public Integer getOrderMath() {
		return this.orderMath;
	}

	public void setOrderMath(Integer orderMath) {
		this.orderMath = orderMath;
	}

	@Column(name = "Nickname", length = 30)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "kanban", length = 50)
	public String getKanban() {
		return this.kanban;
	}

	public void setKanban(String kanban) {
		this.kanban = kanban;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<VotePerson> getVotePersons() {
		return this.votePersons;
	}

	public void setVotePersons(Set<VotePerson> votePersons) {
		this.votePersons = votePersons;
	}

}
